config/routes.rb
Ecoit::Application.routes.draw do

  root 'pages#index'
  
  resources :systems

  resources :network_devices

  resources :softwares

  resources :servers

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'password' => 'passwords#edit'
  post 'user/:id/update_password' => 'passwords#update', as: 'update_password'
  get 'user/:id/reset_password/' => 'passwords#reset', as: "reset_password"

  resources :users, except: :show

  get "index" => 'pages#index'
  get "help" => 'pages#help'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :network_devices
	has_many :servers
	has_many :softwares
	has_many :systems
	
	attr_reader :password, :password_confirmation

	validates :name, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, confirmation: true, length: 6..20, on: :create #只在创建用户时需要对密码进行验证

	before_validation :name_downcase

	def User.authenticate(name, password)
		if user = find_by_name(name)
			if user.password_encrypt == encrypt_password(password)
				user
			end
		end
	end

	def User.encrypt_password(password)
		Digest::SHA2.hexdigest(password + "VincentJiang")
	end

	# 'password' is a virtual attribute
	def password=(password)
		@password = password
		if password.present?
			self.password_encrypt = self.class.encrypt_password(password)
		end
	end

	private
		def name_downcase
			self.name = name.downcase
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout 'main', only: :index

  before_action :is_admin, only: [:index, :new, :create, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :only_update_yourself, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:name)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(create_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: "用户 #{@user.name} 创建成功！" }
        format.json { render action: 'index', status: :created, location: @users }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|

      if current_user.admin && @user != current_user
        update_params = params.require(:user).permit(:email, :admin)
        if @user.update(update_params)
          format.html { redirect_to users_path, notice: "用户 #{@user.name} 修改成功！" }
        else
          format.html { render action: 'edit' }
        end

      elsif current_user.admin && @user == current_user
        update_params = params.require(:user).permit(:email)
        if @user.update(update_params)
          format.html { redirect_to edit_user_path(current_user), notice: "用户 #{@user.name} 修改成功！" }
        else
          format.html { render action: 'edit' }
        end

      else
        update_params = params.require(:user).permit(:email)
        if @user.update(update_params)
          format.html { redirect_to edit_user_path(current_user), notice: "用户 #{@user.name} 修改成功！" }
        else
          format.html { render action: 'edit' }
        end

      end

    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "用户 #{@user.name} 删除成功！" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def is_admin
      redirect_to index_path, alert: "您不是管理员！" unless current_user.admin
    end

    def only_update_yourself
      redirect_to edit_user_path(current_user), alert: "您不能修改别人的资料！" if !current_user.admin && @user != current_user
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= provide :title, "修改用户" %>

<h1 class="text-myBlue">修改用户</h1>

<div class="row">
	
	<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
		<div class="col-sm-6">

		  <div class="form-group">
		    <%= f.label :name, "用户名", class: "control-label col-sm-4" %>
		    <div class="col-sm-8">
		      <%= f.text_field :name, class: "form-control", placeholder: "Login account", disabled: true %>
		    </div>
		  </div>

		  <div class="form-group">
		    <%= f.label :email, "邮箱", class: "control-label col-sm-4" %>
		    <div class="col-sm-8">
		      <%= f.text_field :email, class: "form-control", placeholder: "username@example.com", required: true %>
		    </div>
		  </div>
			
			<% if current_user.admin && @user != current_user %>
			  <div class="form-group">
			    <%= f.label :admin, "权限", class: "control-label col-sm-4" %>
			    <div class="col-sm-8">
		    		<%= f.select :admin, [["管理员", true], ["普通用户", false]], {}, class: "form-control", required: true %>
			    </div>
			  </div>
			<% end %>	
		  <br>

		  <div class="form-group">
		    <div class="col-sm-offset-4 col-sm-8">
		      <%= f.submit "确认修改", class: "btn btn-primary", data: { :disable_with => '正在提交...' } %>
		      <% if current_user.admin %>
		      	<%= link_to '返回', users_path, class: "btn btn-link" %>
		      <% else %>
		      	<%= link_to '返回', index_path, class: "btn btn-link" %>
		      <% end %>
		      
		    </div>
		  </div>
		</div>

		<div class="col-sm-5">
			<% if @user == current_user %>
				<br>
				<a href="<%= password_path %>" class="btn btn-success btn-lg col-sm-offset-2">更改密码 <i class="fa fa-arrow-circle-right"></i></a>
				<br>
			<% end %>
		</div>
	<% end %>
	
</div>

		

app/views/users/index.html.erb
<% content_for :title, "用户列表" %>


<h1 class="text-myBlue">用户列表</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>用户名</th>
        <th>邮箱</th>
        <th>权限</th>
        <th>动作</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.admin ? "管理员" : "普通用户" %></td>
          <td>

            <%= link_to edit_user_path(user), class: "btn btn-warning btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "修改" do %>
              <i class="fa fa-pencil"></i>
            <% end %>

            <%= link_to reset_password_path(user), data: { confirm: "重置密码为 999999 吗？" }, class: "btn btn-info btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "重置密码" do %>
              <i class="fa fa-key"></i>
            <% end %>

            <% unless user == current_user %>
              <%= link_to user, method: :delete, data: { confirm: "删除用户 #{user.name} 吗？" }, class: "btn btn-danger btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "删除" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            <% end %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'layouts/pagination' %>

<% content_for :sidebar do %>
  <div class="text-center" style="margin-top: 70px;">
    <%= link_to new_user_path, class: "btn btn-success" do%>
    新建用户 <i class="fa fa-arrow-circle-right"></i>
    <% end %>
  </div>
<% end %>
    

app/views/users/new.html.erb
<%= provide :title, "新建用户" %>

<h1 class="text-myBlue">新建用户</h1>

<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>

  <div class="form-group">
    <%= f.label :name, "用户名",class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control", placeholder: "新建后便不能修改" %>
    </div>
    <div class="col-sm-4">
      <% if @user.errors[:name].any? %>
        <span class="help-block text-danger"><p class="text-danger"><%= @user.errors.full_messages_for(:name)[0] %></p></span>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, "邮箱", class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.text_field :email, class: "form-control", placeholder: "username@example.com" %>
    </div>
    <div class="col-sm-4">
      <% if @user.errors[:email].any? %>
        <span class="help-block text-danger"><p class="text-danger"><%= @user.errors.full_messages_for(:email)[0] %></p></span>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :admin, "权限", class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.select :admin, [["管理员", true], ["普通用户", false]], {}, class: "form-control" %>
    </div>
    <div class="col-sm-4">
      <% if @user.errors[:admin].any? %>
        <span class="help-block text-danger"><p class="text-danger"><%= @user.errors.full_messages_for(:admin)[0] %></p></span>
      <% end %>
    </div>
  </div>

  <div class="form-group">

    <%= f.label :password, "密码", class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.password_field :password, class: "form-control", placeholder: "长度至少为6个字符" %>
    </div>
    <div class="col-sm-4">
      <% if @user.errors[:password].any? %>
        <span class="help-block text-danger"><p class="text-danger"><%= @user.errors.full_messages_for(:password)[0] %></p></span>
      <% end %>
    </div>

  </div>

  <div class="form-group">

    <%= f.label :password_confirmation, "确认密码", class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="col-sm-4">
      <% if @user.errors[:password_confirmation].any? %>
        <span class="help-block text-danger"><p class="text-danger"><%= @user.errors.full_messages_for(:password_confirmation)[0] %></p></span>
      <% end %>
    </div>

  </div>

  <br>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit "提交", class: "btn btn-primary", data: { :disable_with => '正在提交...' } %>
      <%= link_to '返回', users_path, class: "btn btn-link" %>
    </div>
  </div>

<% end %>