config/routes.rb
Ecoit::Application.routes.draw do

  root 'pages#index'
  
  resources :systems

  resources :network_devices

  resources :softwares

  resources :servers

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'password' => 'passwords#edit'
  post 'user/:id/update_password' => 'passwords#update', as: 'update_password'
  get 'user/:id/reset_password/' => 'passwords#reset', as: "reset_password"

  resources :users, except: :show

  get "index" => 'pages#index'
  get "help" => 'pages#help'

end

app/models/software.rb
class Software < ActiveRecord::Base
	belongs_to :user
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  layout 'main', only: :index
  
  before_action :set_software, only: [:show, :edit, :update, :destroy]

  # GET /softwares
  # GET /softwares.json
  def index
    @softwares = Software.all
  end

  # GET /softwares/1
  # GET /softwares/1.json
  def show
  end

  # GET /softwares/new
  def new
    @software = Software.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @software = Software.new(software_params)

    respond_to do |format|
      if @software.save
        format.html { redirect_to @software, notice: 'Software was successfully created.' }
        format.json { render action: 'show', status: :created, location: @software }
      else
        format.html { render action: 'new' }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    respond_to do |format|
      if @software.update(software_params)
        format.html { redirect_to @software, notice: 'Software was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    @software.destroy
    respond_to do |format|
      format.html { redirect_to softwares_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def software_params
      params.require(:software).permit(:name, :kind, :sn, :service_expired_day, :function, :remark, :user_id)
    end
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/softwares/edit.html.erb
<% content_for :title, "修改软件信息" %>

<h1 class="text-myBlue">修改软件信息</h1>

<%= form_for(@software, html: { class: "form-horizontal" }) do |f| %>

  <div class="form-group">
    <%= f.label :name, "软件名称：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :kind, "软件类型：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :kind, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sn, "SN号：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :sn, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :service_expired_day, "服务到期日期：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.date_select :service_expired_day, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :function, "设备用途：", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :function, class: "form-control", rows: "5" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :remark, "备注：", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :remark, class: "form-control", rows: "5" %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit "提交", :disable_with => '正在提交...', class: "btn btn-primary" %><%= link_to 'Back', softwares_path, class: "btn btn-link" %>
    </div>
  </div>

<% end %>

app/views/softwares/index.html.erb
<% content_for :title, "软件列表" %>


<h1 class="text-myBlue">软件列表</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>软件名称</th>
        <th>软件类型</th>
        <th>SN号</th>
        <th>服务到期日期</th>
        <th>动作</th>
      </tr>
    </thead>

    <tbody>
      <% @softwares.each do |software| %>
        <tr>
          <td><%= software.name %></td>
          <td><%= software.kind %></td>
          <td><%= software.sn %></td>
          <td><%= software.service_expired_day %></td>
          <td>
            <%= link_to software, class: "btn btn-success btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "详情" do %>
              <i class="fa fa-eye"></i>
            <% end %>
            <%= link_to edit_software_path(software), class: "btn btn-warning btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "修改" do %>
              <i class="fa fa-pencil"></i>
            <% end %>
            <%= link_to software, method: :delete, data: { confirm: "删除服务器 #{software.name} 吗？" }, class: "btn btn-danger btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "删除" do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'layouts/pagination' %>

<% content_for :sidebar do %>
  <div class="text-center" style="margin-top: 70px;">
    <%= link_to new_software_path, class: "btn btn-success" do%>
    新建软件信息 <i class="fa fa-arrow-circle-right"></i>
    <% end %>
  </div>
<% end %>

app/views/softwares/new.html.erb
<% content_for :title, "新建软件信息" %>

<h1 class="text-myBlue">新建软件信息</h1>

<%= form_for(@software, html: { class: "form-horizontal" }) do |f| %>

  <div class="form-group">
    <%= f.label :name, "软件名称：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :kind, "软件类型：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :kind, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sn, "SN号：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :sn, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :service_expired_day, "服务到期日期：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.date_select :service_expired_day, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :function, "软件用途：", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :function, class: "form-control", rows: "5" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :remark, "备注：", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :remark, class: "form-control", rows: "5" %>
    </div>
  </div>

  <%= f.hidden_field :user_id, class: "form-control", value: "#{current_user.id}" %>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit "提交", :disable_with => '正在提交...', class: "btn btn-primary" %><%= link_to 'Back', softwares_path, class: "btn btn-link" %>
    </div>
  </div>

<% end %>

app/views/softwares/show.html.erb
<% content_for :title, "查看软件信息" %>

<h1 class="text-myBlue">
  查看软件信息
  <div class="pull-right">
    <a href="<%= edit_software_path(@software) %>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> 修改</a>
    <a href="<%= softwares_path %>" class="btn btn-sm btn-link"><i class="fa fa-arrow-circle-o-left"></i> 返回</a>
  </div>
</h1>

<div class="detail">

  <div class="row">
    <label class="col-sm-2">软件名称：</label><p class="col-sm-10"><%= @software.name %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">软件类型：</label><p class="col-sm-10"><%= @software.kind %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">SN号：</label><p class="col-sm-10"><%= @software.sn %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">服务到期日期：</label><p class="col-sm-10"><%= @software.service_expired_day %></p>
  </div>
  <% if @software.function.present? %>
    <div class="row">
      <label class="col-sm-2">软件用途：</label><p class="col-sm-10"><%= @software.function %></p>
    </div>
  <% end %>
  <% if @software.remark.present? %>
    <div class="row">
      <label class="col-sm-2">备注：</label><p class="col-sm-10"><%= @software.remark %></p>
    </div>
  <% end %>
  <div class="row">
    <label class="col-sm-2">创建者：</label><p class="col-sm-10"><%= @software.user.name %></p>
  </div>

</div>