config/routes.rb
Ecoit::Application.routes.draw do

  root 'pages#index'
  
  resources :systems

  resources :network_devices

  resources :softwares

  resources :servers

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'password' => 'passwords#edit'
  post 'user/:id/update_password' => 'passwords#update', as: 'update_password'
  get 'user/:id/reset_password/' => 'passwords#reset', as: "reset_password"

  resources :users, except: :show

  get "index" => 'pages#index'
  get "help" => 'pages#help'

end

app/models/network_device.rb
class NetworkDevice < ActiveRecord::Base
	belongs_to :user
end

app/controllers/network_devices_controller.rb
class NetworkDevicesController < ApplicationController
  layout 'main', only: :index
  
  before_action :set_network_device, only: [:show, :edit, :update, :destroy]

  # GET /network_devices
  # GET /network_devices.json
  def index
    @network_devices = NetworkDevice.all
  end

  # GET /network_devices/1
  # GET /network_devices/1.json
  def show
  end

  # GET /network_devices/new
  def new
    @network_device = NetworkDevice.new
  end

  # GET /network_devices/1/edit
  def edit
  end

  # POST /network_devices
  # POST /network_devices.json
  def create
    @network_device = NetworkDevice.new(network_device_params)

    respond_to do |format|
      if @network_device.save
        format.html { redirect_to @network_device, notice: 'Network device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @network_device }
      else
        format.html { render action: 'new' }
        format.json { render json: @network_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /network_devices/1
  # PATCH/PUT /network_devices/1.json
  def update
    respond_to do |format|
      if @network_device.update(network_device_params)
        format.html { redirect_to @network_device, notice: 'Network device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @network_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /network_devices/1
  # DELETE /network_devices/1.json
  def destroy
    @network_device.destroy
    respond_to do |format|
      format.html { redirect_to network_devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network_device
      @network_device = NetworkDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_device_params
      params.require(:network_device).permit(:name, :ip, :kind, :place, :position, :sn, :service_expired_day, :function, :remark, :user_id)
    end
end

app/helpers/network_devices_helper.rb
module NetworkDevicesHelper
end

app/views/network_devices/edit.html.erb
<% content_for :title, "修改网络设备" %>

<h1 class="text-myBlue">修改网络设备</h1>

<%= form_for(@network_device, html: { class: "form-horizontal" }) do |f| %>

  <div class="form-group">
    <%= f.label :name, "设备名：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ip, "IP地址：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :ip, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :kind, "设备类型：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :kind, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sn, "SN号：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :sn, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :service_expired_day, "服务到期日期：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.date_select :service_expired_day, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :place, "安装地点：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :place, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, "安装具体位置：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :position, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :function, "设备用途：", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :function, class: "form-control", rows: "5" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :remark, "备注：", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :remark, class: "form-control", rows: "5" %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit "提交", :disable_with => '正在提交...', class: "btn btn-primary" %><%= link_to 'Back', network_devices_path, class: "btn btn-link" %>
    </div>
  </div>

<% end %>

app/views/network_devices/index.html.erb
<% content_for :title, "网络设备列表" %>


<h1 class="text-myBlue">网络设备列表</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>设备名</th>
        <th>IP地址</th>
        <th>设备类型</th>
        <th>SN号</th>
        <th>服务到期日期</th>
        <th>动作</th>
      </tr>
    </thead>

    <tbody>
      <% @network_devices.each do |network_device| %>
        <tr>
          <td><%= network_device.name %></td>
          <td><%= network_device.ip %></td>
          <td><%= network_device.kind %></td>
          <td><%= network_device.sn %></td>
          <td><%= network_device.service_expired_day %></td>
          <td>
            <%= link_to network_device, class: "btn btn-success btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "详情" do %>
              <i class="fa fa-eye"></i>
            <% end %>
            <%= link_to edit_network_device_path(network_device), class: "btn btn-warning btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "修改" do %>
              <i class="fa fa-pencil"></i>
            <% end %>
            <%= link_to network_device, method: :delete, data: { confirm: "删除服务器 #{network_device.name} 吗？" }, class: "btn btn-danger btn-xs show-tootip", "data-toggle" => "tooltip", "data-placement" => "top", title: "删除" do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'layouts/pagination' %>

<% content_for :sidebar do %>
  <div class="text-center" style="margin-top: 70px;">
    <%= link_to new_network_device_path, class: "btn btn-success" do%>
    新建网络设备 <i class="fa fa-arrow-circle-right"></i>
    <% end %>
  </div>
<% end %>

app/views/network_devices/new.html.erb
<% content_for :title, "新建网络设备" %>

<h1 class="text-myBlue">新建网络设备</h1>

<%= form_for(@network_device, html: { class: "form-horizontal" }) do |f| %>

  <div class="form-group">
    <%= f.label :name, "设备名：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ip, "IP地址：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :ip, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :kind, "设备类型：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :kind, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sn, "SN号：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :sn, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :service_expired_day, "服务到期日期：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.date_select :service_expired_day, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :place, "安装地点：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :place, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, "安装具体位置：", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :position, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :function, "设备用途：", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :function, class: "form-control", rows: "5" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :remark, "备注：", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :remark, class: "form-control", rows: "5" %>
    </div>
  </div>

  <%= f.hidden_field :user_id, class: "form-control", value: "#{current_user.id}" %>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit "提交", :disable_with => '正在提交...', class: "btn btn-primary" %><%= link_to 'Back', network_devices_path, class: "btn btn-link" %>
    </div>
  </div>

<% end %>

app/views/network_devices/show.html.erb
<% content_for :title, "查看网络设备" %>

<h1 class="text-myBlue">
  查看网络设备
  <div class="pull-right">
    <a href="<%= edit_network_device_path(@network_device) %>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> 修改</a>
    <a href="<%= network_devices_path %>" class="btn btn-sm btn-link"><i class="fa fa-arrow-circle-o-left"></i> 返回</a>
  </div>
</h1>

<div class="detail">

  <div class="row">
    <label class="col-sm-2">设备名：</label><p class="col-sm-10"><%= @network_device.name %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">IP地址：</label><p class="col-sm-10"><%= @network_device.ip %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">设备类型：</label><p class="col-sm-10"><%= @network_device.kind %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">SN号：</label><p class="col-sm-10"><%= @network_device.sn %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">服务到期日期：</label><p class="col-sm-10"><%= @network_device.service_expired_day %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">安装地点：</label><p class="col-sm-10"><%= @network_device.place %></p>
  </div>
  <div class="row">
    <label class="col-sm-2">安装具体位置：</label><p class="col-sm-10"><%= @network_device.position %></p>
  </div>
  <% if @network_device.function.present? %>
    <div class="row">
      <label class="col-sm-2">服务器用途：</label><p class="col-sm-10"><%= @network_device.function %></p>
    </div>
  <% end %>
  <% if @network_device.remark.present? %>
    <div class="row">
      <label class="col-sm-2">备注：</label><p class="col-sm-10"><%= @network_device.remark %></p>
    </div>
  <% end %>
  <div class="row">
    <label class="col-sm-2">创建者：</label><p class="col-sm-10"><%= @network_device.user.name %></p>
  </div>

</div>