config/routes.rb
Ecoit::Application.routes.draw do

  root 'pages#index'
  
  resources :systems

  resources :network_devices

  resources :softwares

  resources :servers

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'password' => 'passwords#edit'
  post 'user/:id/update_password' => 'passwords#update', as: 'update_password'
  get 'user/:id/reset_password/' => 'passwords#reset', as: "reset_password"

  resources :users, except: :show

  get "index" => 'pages#index'
  get "help" => 'pages#help'

end

app/views/layouts/_footer.html.erb
<p class="text-center"><i class="fa fa-heart" style="color: #f00;"></i> 为了您最佳的网页浏览体验，请使用 <a href="https://www.google.com/intl/zh-CN/chrome/browser/?hl=zh-CN&brand=CHMI" target="_blank"><i>Chrome</i></a> 浏览器</p>
<p>
	<ul class="list-inline text-center">
		<li><i class="fa fa-star" style="color: #f90;"></i> Designed by VincentJiang</li>
		<li><i class="fa fa-github"></i> <a href="https://github.com/vincentjiang/ecoit" target="_blank">Github</a></li>
		<li><i class="fa fa-envelope-o"></i> <a href="mailto:jxs471494539@gmail.com?subject=ECO IT System">Contact me</a></li>
	</ul>
</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}", class: "text-center" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav id="top" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-home fa-fw"></i> ECO IT System
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_left_links' %>
      </ul>

      <div class="col-sm-4 navbar-left">
        <form class="navbar-form" role="search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="搜索用户、资产或文档">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
          </div>
        </div>
        </form>
        </div>


      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_right_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_left_links.html.erb
<% if session[:user_id] %>
	<li class="dropdown">
		<%= link_to root_path, class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
		资产 <b class="caret"></b>
		<% end %>
		<ul class="dropdown-menu">
      <li><%= link_to '服务器', servers_path %></li>
      <li><%= link_to '网络设备', network_devices_path %></li>
      <li><%= link_to '软件', softwares_path %></li>
      <li><%= link_to '应用系统', systems_path %></li>
    </ul>
	</li>
	<li><%= link_to '文档', root_path %></li>
	<% if current_user.admin %>
		<li><%= link_to '用户', users_path %></li>
	<% end %>
<% end %>
<li><%= link_to '帮助', help_path %></li>

<script type="text/javascript">
	$(function() {
	  // dropdown
	  $('a').hover(function() {
	  	$(this).parent('li').addClass('open').siblings('li').removeClass('open');
	  });

	});
</script>

app/views/layouts/_navigation_right_links.html.erb
<% if session[:user_id] %>
	<li>
		<%= link_to edit_user_path(current_user), class: "show-tootip", "data-toggle" => "tooltip", "data-placement" => "bottom", title: "#{current_user.name}" do %>
			<i class="fa fa-user"></i>
		<% end %>
	</li>
	<li>
		<%= link_to logout_path, class: "show-tootip", "data-toggle" => "tooltip", "data-placement" => "bottom", title: "登出", data: { confirm: "退出系统？" } do %>
			<i class="fa fa-power-off"></i>
		<% end %>
	</li>
<% else %>
	<li>
		<%= link_to login_path, class: "show-tootip", "data-toggle" => "tooltip", "data-placement" => "bottom", title: "登录" do %>
			登录 <i class="fa fa-sign-in"></i>
		<% end %>
	</li>
<% end %>

<script type="text/javascript">
	$(function() {
	  // tooltip
	  $('.show-tootip').tooltip();

	});
</script>

app/views/layouts/_pagination.html.erb
<div class="pull-right">
  <ul class="pagination">
    <li class="disabled"><a href="#">&laquo;</a></li>
    <li class="active"><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">&raquo;</a></li>
  </ul>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8" />
    <%= favicon_link_tag 'towngas_logo.jpg' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ECOIT" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "ECOIT" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>

      <%= render 'layouts/navigation' %>
    
    </header>

    <main id="main" role="main">
      <div class="container">

        <%= render 'layouts/messages' %>

        <%= yield %>

      </div>

    </main>

    <%#= debug(params) if Rails.env.development? %>

    <footer>
      <div class="container">

        <%= render 'layouts/footer' %>

      </div>
    </footer>

  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8" />
    <%= favicon_link_tag 'towngas_logo.jpg' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ECOIT" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "ECOIT" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>

      <%= render 'layouts/navigation' %>
    
    </header>

    <main id="main" role="main">
      <div class="container">

        <div class="row">
          
          <div class="col-md-9">
            <%= render 'layouts/messages' %>

            <%= yield %>
          </div>

          <div class="col-md-3">
            <%= yield :sidebar %>
          </div>

        </div>

      </div>

    </main>

    <%#= debug(params) if Rails.env.development? %>

    <footer>
      <div class="container">

        <%= render 'layouts/footer' %>

      </div>
    </footer>

  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8" />
    <%= favicon_link_tag 'towngas_logo.jpg' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ECOIT" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "ECOIT" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>

      <%= render 'layouts/navigation' %>
    
    </header>

    <main id="main" role="main">
      <div class="container">

        <%= render 'layouts/messages' %>

        <div class="row">
  
          <div class="col-sm-3">
            <%= render  'layouts/sidebar' %>
          </div>

          <div class="col-sm-9">

            <%= yield %>
          </div>

        </div>

      </div>

    </main>

    <%= debug(params) if Rails.env.development? %>

    <footer>
      <div class="container">

        <%= render 'layouts/footer' %>

      </div>
    </footer>

    <script type="text/javascript">
      $(function() {
        // tooltip
        $('.show-tootip').tooltip();

      });
    </script>

  </body>
</html>